import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/compponent/header/header";
import Footer from "@/compponent/footer/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const Light = localFont({
  src: "./fonts/Farsi numerals/IRANSansXFaNum-Light.ttf",
  variable: "--Light",
});
const mediumNumber = localFont({
  src: "./fonts/Farsi numerals/IRANSansXFaNum-Medium.ttf",
  variable: "--mediumNumber",
});
const javan = localFont({
  src: "./fonts/javan.ttf",
  variable: "--javan",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="fa">
      <body
        className={`${geistSans.variable} ${mediumNumber.variable} ${javan.variable} ${Light.variable} ${geistMono.variable} antialiased px-24`}
      >
        <header>
           <Header/>
        </header>
       

          {children}     
       
      </body>
     
    </html>
  );
}
